version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fs-frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fs-backend
    restart: unless-stopped
    environment:
      PORT: 5002

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: fs-tunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - frontend