version: "3"

services:

  web:
    image: nginx:alpine
    container_name: fs-web
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: fs-tunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - web