version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_EMAILJS_SERVICE_ID: ${VITE_EMAILJS_SERVICE_ID}
        VITE_EMAILJS_TEMPLATE_CONTACT: ${VITE_EMAILJS_TEMPLATE_CONTACT}
        VITE_EMAILJS_TEMPLATE_REPLY: ${VITE_EMAILJS_TEMPLATE_REPLY}
        VITE_EMAILJS_PUBLIC_KEY: ${VITE_EMAILJS_PUBLIC_KEY}
    container_name: fs-frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fs-backend
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: fs-tunnel
    command: tunnel run --token ${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - frontend